### ISSUE TITLE
check updatecontent needs fd limit

### ISSUE THREAD

**Issue by gabibeyer** [clearlinux/diva#82]
The check updatecontent command is failing while trying to open an excessive amount of files. Modify this to not allow that to happen.

**Comment by matthewrsj** [comment]
I limited the concurrency quite a bit already to solve this issue. Any ideas to dynamically limit? It's tough because the go runtime doesn't know about how many fds the threads are opening, it only schedules against cpu load. Doesn't seem like a good solution to read maxfds from the filesystem either, since we can never guarantee that diva is the only thing opening files.

Open to suggestions. I don't really want to just keep decreasing parallelism as we see this issue pop up on random machines, but that may be my only choice.

Maybe some sort of mechanism that locks a mutex at a certain number of open fds? Not quite sure what that would look like though.

**Comment by tmarcu** [comment]
I assume this kind of thing:
https://github.com/clearlinux/diva/blob/master/updatecontent/updatecontent.go#L55
is what's actually running out of FD's. This is entirely too many if we open one go routine per file, this should be limited to `runtime.NumCPU()` or a multiple of that at most. The rest are all clamped to numbers that won't run out right now, but e.g once we have more bundles than FD's per process that will also fail.

**Comment by gabibeyer** [comment]
Fixed in PR #133 - thank you to @tmarcu  🎉
